name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to main branch

permissions:
  contents: read
  pages: write
  id-token: write  # Required for OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Upload all files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
