name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to main branch

permissions:
  contents: read
  pages: write
  id-token: write  # Required for GitHub Pages OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Files
        uses: actions/upload-pages-artifact@v4  # Updated to v4
        with:
          path: "."  # Ensure this points to the correct location of index.html
          name: github-pages  # Define artifact name explicitly

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # Match artifact name
