name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest  # Will automatically use ubuntu-24 after migration

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -la

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Files
        uses: actions/upload-pages-artifact@v3  # ✅ Updated to v3
        with:
          path: "./"  # Ensure this points to the directory containing index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # ✅ Updated to v4
